Fix go 1.18 installation compatibility issue
grpc-ecosystem/protoc-gen-grpc-gateway-ts pull request #37
Opened 2022-06-16 08:47 UTC by wilsonwu

Fix go 1.18 installation compatibility issue:
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/1269496/174031371-64f64411-56dc-4225-ae0e-cf7ebc92c84d.png">

solve #33

2022-06-16 10:01 UTC, wilsonwu commented
@lyonlai please help to review and merge, thank you very much!

2022-06-17 03:35 UTC, lyonlai commented
thanks for the contribution @wilsonwu . I'll take a look soon

2022-06-17 04:08 UTC, lyonlai requested changes
changes LGTM but the build's failing. will require some extra effort from you. @wilsonwu

2022-06-17 07:40 UTC, wilsonwu commented
@lyonlai seems the job broken for long time, I tried to solve it, please help to run it.

2022-06-20 08:22 UTC, wilsonwu commented
@lyonlai please help to rerun, already fixed in my repo:
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/1269496/174558032-fdd69a2e-cf5f-4134-a2dd-51c82a0bbf33.png">

2022-06-20 09:40 UTC, lyonlai requested changes
missing the go-releaser for 1.18. others LGTM

2022-06-20 09:40 UTC, lyonlai commented on .github/workflows/main.yml
> +          go-version: 1.17
might as well change this to 1.18?

2022-06-21 03:45 UTC, wilsonwu commented on .github/workflows/main.yml
> +          go-version: 1.17
make sense

2022-06-21 05:58 UTC, wilsonwu commented on .github/workflows/main.yml
> +          go-version: 1.17
Anything else I need to do for go-releaser? Sorry for that I have no experience on such cases.

2022-06-21 22:02 UTC, lyonlai approved these changes

2022-06-21 22:04 UTC, lyonlai commented
Thanks you for your. contribution @wilsonwu

2022-06-21 22:04 UTC, merged